sudo: required
language: bash
dist: xenial
services:
  - docker

script:
  # build the Docker image using the Docker tool, osc cannot be easily used in Travis
  - cd package
  - docker build -t libstorage-ng-test-image .

